services:
  frontend:
      build:
        context: ./prueba-tecnica-frontend
        dockerfile: Dockerfile
      container_name: prueba-tecnica-frontend
      restart: always
      ports:
        - "${FRONTEND_PORT:-8000}:80"
      environment:
        - VITE_API_URL=http://prueba-tecnica-backend:${API_PORT}/api
      depends_on:
        - backend
  backend:
    build:
      context: ./prueba-tecnica-backend
      dockerfile: Dockerfile
    container_name: prueba-tecnica-backend
    restart: always
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - NODE_ENV=production
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db

  db:
    image: postgres:14.3
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: ${DB_HOST}
    volumes:
      - ./postgres:/var/lib/postgresql/data
